config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :omniauth_callbacks => 'users/omniauth_callbacks' 
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  root 'posts#index'
  get 'users/:id', to: 'users#show', as: 'user'
  get 'users/', to: 'users#index', as: 'user_index'
  
  # resources :users, only: %i(index show)
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :posts, only: %i(new create index show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
  end
  
  resources :relationships, only: %i(create destroy)
  resources :notifications, only: :index
  
end

app/views/partial/_count_follower.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/partial/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'post', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/partial/_footer.html.erb
<footer>
  
  <nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <div class="text-center">
        <p>
          Copyright © 
        </p>
      </div>
      
      <ul class="navbar-nav ml-md-auto align-items-center">
        
        <li>
          <%= link_to "写真を投稿する", new_post_path, class: "btn btn-light" %>
        </li>
        
      </ul>
    </div>
  </div>
</nav>
  
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          
          <dl class="searchbox">
            <%= search_form_for @search, url: posts_path, html: { id: :form1 }  do |f| %>
              <%= f.text_field :caption_cont, class: 'sbox', placeholder: '入力...' %>
              <%= f.submit ("検索"), class: 'sbtn' %>
            <% end %>
          </dl>
          
        </li>
        <li>
          <%= link_to "",  user_index_path, class: "nav-link commonNavIcon people-icon" %>
        </li>
        <li class="notification">
          <%= link_to(notifications_path) do %>
            <% if unchecked_notifications.any? %>
              <span class="fa-stack">
                <i class="fa fa-bell fa-lg fa-stack-2x" style="font-size: 1.5em; color: #696969;"></i>
                <i class="fa fa-circle n-circle fa-stack-1x"></i>
              </span>
            <% else %>
              <i class="fa fa-bell fa-lg"  style="font-size: 1.5em; color: #696969;"></i>
            <% end %>
          <% end %>
        </li>
        <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
        </li>
        
      </ul>
    </div>
  </div>
</nav>